mod: 게시판 기능 수정
mung-mung/BE pull request #18
Opened 2024-05-13 09:14 UTC by joohunhyun

2024-05-14 06:28 UTC, baekgyu-kim requested changes
postDto도 정의해서 실제 응답은 postDto를 통해서 해줘.

2024-05-14 06:28 UTC, baekgyu-kim commented on src/main/java/api/board/PostController.java
> +            return HttpResponse.successOk();
왜 아무 동작도 하지 않고 바로 응답 하는거야 ??

2024-05-14 06:28 UTC, baekgyu-kim commented on src/main/java/api/board/PostController.java
> +            return HttpResponse.badRequest();
여기에는 badRequest 말고 internalError로 응답 메세지, data 추가하면 좋을듯

2024-05-14 06:28 UTC, baekgyu-kim commented on src/main/java/api/board/PostController.java
> +
여기는 구현 아직 안된건가??

2024-05-14 06:28 UTC, baekgyu-kim commented on src/main/java/api/board/PostService.java
> +
여기에다가 실제 로직 구현하면 돼.

2024-05-15 06:11 UTC, baekgyu-kim requested changes
code에 comment 달아 놓은 부분 수정해서 새로 푸시하면 PR에 자동으로 반영돼 !!
수정해서 푸시해주고 완료되면 카톡방에 알려줘
그리고 수정 사항 하나 완료할 때마다 커밋/푸시 수시로 자주 해줘 ㅋㅋㅋㅋ

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/PostController.java
> +        return postService.getAllPost();
DTO를 생성해서 PostDto을 통해서 응답하도록 수정해줘. 

그리고 응답할 때 HttpResponse 유틸 클래스를 사용해서 그 안의 data에다가 결과 담아서 보내줘야 해. 

다른 코드들 보면 어떻게 하는지 알 수 있을거야.

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/PostController.java
> +        return postService.getPostById(id);
여기서도 dto 형식으로 HttpResponse에 담아서 응답해줘.

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/PostController.java
> +        Post post = postService.createPost(postDto);
여기도 !

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/PostController.java
> +        return postService.updatePost(id, updatedPost);
여기도 !

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/PostController.java
> +        postService.deletePost(id);
여기는 결과 데이터가 없잖아. 그러면 HttpResponse 유틸로 응답하는데 data는 null로 하고 message를 삭제 성공했다는 내용으로 써서 보내면 돼.

다른 코드 보면 어떻게 하는지 알 수 있을거야.

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/PostService.java
> +        return postRepository.findAll();
dto로 변환해서 응답하도록 해줘.

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/PostService.java
> +        return new PostResponseDto(post);
여기는 dto로 잘 응답해준 것 같아 !

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/PostService.java
> +    }
writer은 인자로 받지 말고 LoggedInUser 유틸 클래스 사용해서 받아오도록 수정해줘. 
OwningService에서 deleteOwningById 메소드 코드 보면 감 잡을 수 있을거야.

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/PostService.java
> +    }
이거도 logged in user 유틸 클래스 사용해서 writer만 수정할 수 있도록 수정해줘. 
OwningService에서 deleteOwningById 메소드 코드 보면 감 잡을 수 있을거야.

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/PostService.java
> +    }
이거도 유틸 클래스 사용해서 writer만 삭제할 수 있도록 수정해줘.

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/dto/PostRegisterDto.java
다른 수정 사항들을 고려한다면 이 파일은 없어도 괜찮지 않을까?

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/dto/PostCreateDto.java
postCreateDto랑 postResponseDto랑 통합할 수 있지 않을까? 
그리고 id값도 포함시키면 좋을 것 같아. (생성할 때는 Id를 아직 모르니까 null로 넣어도 괜찮을 것 같아)

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/dto/PostResponseDto.java
postCreateDto랑 postResponseDto랑 통합할 수 있지 않을까? 
그리고 id값도 포함시키면 좋을 것 같아. (생성할 때는 Id를 아직 모르니까 null로 넣어도 괜찮을 것 같아)

2024-05-15 06:11 UTC, baekgyu-kim commented on src/main/java/api/board/dto/PostUpdateDto.java
이거도 가능하다면 dto 하나로 통일시키면 깔끔할 것 같은데 update용 dto는 따로 빼도 상관은 없을 것 같아 !!

2024-05-15 15:48 UTC, whsung0330 commented on src/main/java/api/board/PostService.java
> +        return postRepository.findAll();
컨트롤러, 서비스에서 DTO로 변환하는 과정은 dog 관련 코드 확인해보면 될거 같아!

2024-05-15 15:48 UTC, whsung0330 commented on src/main/java/api/board/dto/PostCreateDto.java
postCreateDto는 지금 쓰이지 않고 PostRegisterDto랑 같은 역할을 하는거 같으니 삭제해도 될거 같아.

2024-05-15 15:48 UTC, whsung0330 commented on src/main/java/api/board/dto/PostResponseDto.java
PostResponseDto가 저장된 글을 가져와서 보여주는 역할을 하는걸로 이해했는데, 그러면 PostCreateDto (PostRequestDto)랑 구분되는게 맞는거 같아. 
그리고 createdAt/updatedAt도 포함해야 할듯

2024-05-15 15:48 UTC, whsung0330 commented on src/main/java/api/board/dto/PostUpdateDto.java
Post 엔티티에서 이미 update 메서드가 정의되어 있고, 서비스에서도 PostRequestDto랑 post.update를 사용해서 수정하고 있으니 PostUpdateDto는 필요 없을거같아.

2024-05-15 15:49 UTC, whsung0330 commented on src/main/java/api/board/dto/PostRegisterDto.java
이걸 남기고 PostCreateDto를 삭제하는게 맞는듯

2024-05-16 06:48 UTC, baekgyu-kim commented on src/main/java/api/board/dto/PostResponseDto.java
DTO라서 createdAt/updatedAt는 없어도 될듯 ! 
그리고 PostCreateDto랑 PostRequestDto는 id를 null로 넣어주기만 하면 통합할 수 있지 않을까??

2024-05-21 08:54 UTC, merged